// client/src/app/loading/loading.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-loading',
  templateUrl: './loading.component.html',
  styleUrls: ['./loading.component.scss']
})
export class LoadingComponent {
  constructor() {
  }
}

<div class="loading">
  <span class="mdl-spinner mdl-js-spinner is-active"></span>
  <span class="loading__text">loading...</span>
</div>

// client/src/js/component/Loading.jsx
import React from 'react';

class Loading extends React.Component {
  render() {
    return (
      <div className="loading">
        <span className="mdl-spinner mdl-js-spinner is-active"></span>
        <span className="loading__text">loading...</span>
      </div>
    );
  }
}

export default Loading;
